name: Release
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup release please
        uses: google-github-actions/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          changelog-path: CHANGELOG.md
          package-name: forest-night-jetbrains
      # The logic below handles JetBrains publication:
      - uses: actions/setup-java@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          java-version: 11
      - uses: actions/cache@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build plugin
        if: ${{ steps.release.outputs.release_created }}
        run: ./gradlew buildPlugin --stacktrace
      - name: Verify plugin
        if: ${{ steps.release.outputs.release_created }}
        run: ./gradlew verifyPlugin --stacktrace
      - name: Publish plugin
        if: ${{ steps.release.outputs.release_created }}
        run: ./gradlew publishPlugin --stacktrace
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
